import "jspdf-autotable";
import autoTable from "jspdf-autotable";
import { PdfEngine } from "@/components/pdf-layout-design/PdfEngine";
import { pdfTemplateService } from "@/components/pdf-layout-design/services/pdf-template";
import { PAPER_SIZES } from "@/components/pdf-layout-design/constants";
import type { Customer, SalesmanWithRelations } from "../types";

type CompanyData = Record<string, unknown>;

async function fetchCompanyData(): Promise<CompanyData | null> {
    try {
        const res = await fetch("/api/pdf/company", { credentials: "include" });
        if (!res.ok) return null;
        const result = await res.json();
        return result.data?.[0] ?? null;
    } catch {
        return null;
    }
}

function formatDateTime(value: Date): string {
    return value.toLocaleString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
    });
}

function safeFilePart(value: string): string {
    return value.replace(/[\\/:*?\"<>|]+/g, "-").trim();
}

export async function exportSalesmanCustomersPDF(params: {
    salesman: SalesmanWithRelations;
    customers: Customer[];
    generatedBy?: string;
}): Promise<void> {
    const { salesman, customers, generatedBy } = params;

    const now = new Date();
    const dateStr = formatDateTime(now);
    const fileName = `Salesman_Customers_${safeFilePart(salesman.salesman_code || "")}_${now
        .toISOString()
        .slice(0, 10)}.pdf`;

    const [companyData, templates] = await Promise.all([
        fetchCompanyData(),
        pdfTemplateService.fetchTemplates(),
    ]);

    const templateName =
        templates.find((t: { name: string }) => t.name === "Header")?.name ||
        templates[0]?.name ||
        "Salesman Customer Printables";

    const divisionName = salesman.division?.division_name ?? "";
    const warehouseName = salesman.branch?.branch_name ?? "";

    const tableRows = customers.map((c) => {
        const location = [c.province, c.city, c.brgy]
            .filter((p) => Boolean(p && String(p).trim().length > 0))
            .join(", ");

        return [
            c.customer_code || "—",
            c.customer_name || "—",
            c.store_name || "—",
            c.store_signage || "—",
            location || "—",
            c.contact_number || "—",
        ];
    });

    const doc = await PdfEngine.generateWithFrame(templateName, companyData, (doc, startY, config) => {
        const margins = config.margins || { top: 10, bottom: 10, left: 10, right: 10 };
        const pageW = doc.internal.pageSize.getWidth();
        const usableW = pageW - margins.left - margins.right;

        // Calculate dynamic bottom margin based on Body End indicator (if present)
        const baseSize =
            config.paperSize === "Custom"
                ? config.customSize
                : PAPER_SIZES[config.paperSize] || PAPER_SIZES.A4;
        const paperHeight = config.orientation === "landscape" ? baseSize.width : baseSize.height;
        const bottomMargin = config.bodyEnd ? paperHeight - config.bodyEnd : margins.bottom;

        let y = startY;

        doc.setFont("helvetica", "bold");
        doc.setFontSize(13);
        doc.setTextColor(20, 20, 20);
        doc.text("Salesman Customer Printables", margins.left, y, { baseline: "top" });

        y += 7;
        doc.setFontSize(10.5);
        doc.text("Salesman Customer", margins.left, y, { baseline: "top" });

        y += 8;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(80, 80, 80);

        const leftX = margins.left;
        const rightX = margins.left + usableW * 0.52;
        const lineH = 5;

        doc.text(`Salesman Code: ${salesman.salesman_code || ""}`, leftX, y, { baseline: "top" });
        doc.text(`Salesman Name: ${salesman.salesman_name || ""}`, rightX, y, { baseline: "top" });
        y += lineH;

        doc.text(`Division: ${divisionName}`, leftX, y, { baseline: "top" });
        doc.text(`Warehouse: ${warehouseName}`, rightX, y, { baseline: "top" });
        y += lineH;

        doc.text(`Date: ${dateStr}`, leftX, y, { baseline: "top" });
        doc.text(`Generated By: ${generatedBy || ""}`, rightX, y, { baseline: "top" });

        y += 7;
        doc.setTextColor(20, 20, 20);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8.5);
        doc.text(`Total Records: ${customers.length}`, margins.left, y, { baseline: "top" });
        doc.setFont("helvetica", "normal");

        // Column widths sum to usableW (A4 portrait default ~190mm)
        const colCode = 22;
        const colCust = 34;
        const colStore = 34;
        const colSignage = 28;
        const colLocation = 45;
        const colContact = usableW - colCode - colCust - colStore - colSignage - colLocation;

        autoTable(doc, {
            startY: y + 6,
            margin: { ...margins, bottom: bottomMargin },
            tableWidth: usableW,
            tableLineWidth: 0.2,
            tableLineColor: [0, 0, 0],
            head: [
                [
                    "Customer Code",
                    "Customer Name",
                    "Store Name",
                    "Store Signage",
                    "Address",
                    "Contact Number",
                ],
            ],
            body: tableRows,
            theme: "striped",
            styles: {
                lineWidth: 0.1,
                lineColor: [0, 0, 0],
            },
            headStyles: {
                fillColor: [41, 128, 185],
                textColor: 255,
                fontSize: 8,
                fontStyle: "bold",
                halign: "left",
                valign: "middle",
                cellPadding: 1.6,
                lineWidth: 0.1,
                lineColor: [0, 0, 0],
            },
            bodyStyles: {
                fontSize: 7.5,
                valign: "top",
                cellPadding: 1.6,
                lineWidth: 0.1,
                lineColor: [0, 0, 0],
            },
            alternateRowStyles: { fillColor: [245, 245, 245] },
            columnStyles: {
                0: { cellWidth: colCode },
                1: { cellWidth: colCust },
                2: { cellWidth: colStore },
                3: { cellWidth: colSignage },
                4: { cellWidth: colLocation },
                5: { cellWidth: colContact },
            },
        });

        // ── Writable line under the table (for manual notes on print) ───────
        const lastTableY = (doc as unknown as { lastAutoTable?: { finalY?: number } }).lastAutoTable
            ?.finalY;
        let notesY = (lastTableY ?? y + 24) + 10;
        const pageH = doc.internal.pageSize.getHeight();
        const notesBlockH = 10;
        const maxY = pageH - bottomMargin;

        if (notesY + notesBlockH > maxY) {
            doc.addPage();
            notesY = margins.top;
        }

        doc.setDrawColor(0, 0, 0);
        doc.setLineWidth(0.2);
        const lineStartX = margins.left;
        const lineEndX = margins.left + usableW;
        const firstLineY = notesY;

        doc.line(lineStartX, firstLineY, lineEndX, firstLineY);
    });

    const blob = doc.output("blob");
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
